version: "3.10"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=userdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Rsonawane13
      - MYSQL_HOST=db

    depends_on:
      - db

  db:
    image: mysql:latest
    volumes:
      - dev-db-data:/usr/local/mysql/bin
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=userdb
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testuser

volumes:
  dev-db-data: